### ISSUE TITLE
Error after conda installation: writing permission denied in the source tree

### ISSUE THREAD

**Issue by loraine-gueguen** [the-mitchell-lab/rodeo2#12]
Hi,
We have installed rodeo2 through bioconda on our computing infrastructure.
With command `rodeo_main.py cyclases_selection.txt -pt lasso -out cyclases_selection_output -c conf`, the user has the following error:

```
Traceback (most recent call last):
  File "/shared/software/miniconda/envs/rodeo-2.3.3/bin/rodeo_main.py", line 409, in <module>
    __main__()
  File "/shared/software/miniconda/envs/rodeo-2.3.3/bin/rodeo_main.py", line 285, in __main__
    module.write_csv_headers(output_dir)
  File "/shared/software/miniconda/envs/rodeo-2.3.3/bin/ripp_modules/lasso/lasso_module.py", line 58, in write_csv_headers
    svm_csv_file = open(os.path.join(FILE_DIR, "svm/fitting_set.csv"), 'w')
PermissionError: [Errno 13] Permission denied: '/shared/software/miniconda/envs/rodeo-2.3.3/bin/ripp_modules/lasso/svm/fitting_set.csv'
```

Indeed, he program tries to write to a file in the source code tree (`ripp_modules/lasso/svm/fitting_set.csv` here, but also similar files in the other ripp_modules), for which it does not have sufficient rights, of course.

How do you manage to operate the tool after conda installation ?
One possible workaround would be to set the location of this file in the command line or the configuration file. What do you think ?

BTW, I don't understand why this error didn't appear with the test command `rodeo2 BAL72546.1 -pt lasso lanthi linar sacti thio -out test_output -c conf`

Regards,

Loraine

**Comment by dslater82** [comment]
Hi Loraine,

We recently fix the issues with it writing to svm folders for the modules.  If you git pull the latest commits, it should work for you now.  We will be releasing a new tag release in the near future.
