### ISSUE TITLE
RRE.py not found

### ISSUE THREAD

**Issue by palamalama** [the-mitchell-lab/rodeo2#28]
Hi, I am trying to install RODEO2, which I have downloaded and installed alongside hmmer and I have added Pfam-A.hmm as per the instructions on the RODEO website. I am trying to run the following command, 
`python rodeo_main.py ACN52311.1 -out thiostrepton`

But I am getting the following error:

> 2023-01-24 00:30:43,559 - rodeo_main - WARNING - Overwriting thiostrepton folder.
2023-01-24 00:30:43,592 - entrez_utils - INFO - Fetching ACN52311.1 data from GenBank.
2023-01-24 00:30:47,481 - entrez_utils - INFO - Parsing ACN52311.1 handle.
2023-01-24 00:30:47,736 - record_processing - INFO - Worker process 1 is processing ACN52311.1
2023-01-24 00:30:47,747 - My_Record - ERROR - RREFinder returned 127: b'/bin/sh: 1: RRE.py: not found\n'
2023-01-24 00:30:47,753 - My_Record - ERROR - RREFinder returned 127: b'/bin/sh: 1: RRE.py: not found\n'
2023-01-24 00:30:47,761 - My_Record - ERROR - RREFinder returned 127: b'/bin/sh: 1: RRE.py: not found\n'
2023-01-24 00:30:47,766 - My_Record - ERROR - RREFinder returned 127: b'/bin/sh: 1: RRE.py: not found\n'
2023-01-24 00:30:47,772 - My_Record - ERROR - RREFinder returned 127: b'/bin/sh: 1: RRE.py: not found\n'
2023-01-24 00:30:47,780 - My_Record - ERROR - RREFinder returned 127: b'/bin/sh: 1: RRE.py: not found\n'
2023-01-24 00:30:47,786 - My_Record - ERROR - RREFinder returned 127: b'/bin/sh: 1: RRE.py: not found\n'
2023-01-24 00:30:47,791 - My_Record - ERROR - RREFinder returned 127: b'/bin/sh: 1: RRE.py: not found\n'
2023-01-24 00:30:47,797 - My_Record - ERROR - RREFinder returned 127: b'/bin/sh: 1: RRE.py: not found\n'
sh: 1: prodigal: not found
2023-01-24 00:30:51,475 - record_processing - ERROR - ERROR FOR ACN52311.1
2023-01-24 00:30:51,475 - record_processing - ERROR - [Errno 2] No such file or directory: '/tmp/FJ652572.1_ILBE6_ig.fasta'
Traceback (most recent call last):
  File "/Desktop/rodeo2/record_processing.py", line 85, in process_record_worker
    record.set_intergenic_orfs(min_aa_seq_length=master_conf['general']['variables']['precursor_min'],
  File "/Desktop/rodeo2/My_Record.py", line 281, in set_intergenic_orfs
    all_orfs = SeqIO.parse(f"/tmp/{self.cluster_accession}_{identifier}_ig.fasta", "fasta")
  File "/usr/local/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
  File "/usr/local/lib/python3.9/site-packages/Bio/SeqIO/FastaIO.py", line 223, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/usr/local/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 45, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/FJ652572.1_ILBE6_ig.fasta'
2023-01-24 00:30:51,477 - record_processing - ERROR - Worker process 1 is moving on
2023-01-24 00:30:51,478 - rodeo_main - INFO - Writing output for query #1.	ACN52311.1
2023-01-24 00:30:51,478 - rodeo_main - ERROR - For ACN52311.1:	[Errno 2] No such file or directory: '/tmp/FJ652572.1_ILBE6_ig.fasta'
2023-01-24 00:30:51,479 - rodeo_main - ERROR - No valid results. Input may be invalid or Genbank may not be responding

My assumption is that the file RRE.py which should be in the base directory is missing, but this may be something else I don't understand. Any ideas?

I literally have just pulled the latest version of the repo, so I definitively haven't deleted any files.

**Comment by bkille** [comment]
It looks like you are missing the RREFinder [dependency](https://github.com/the-mitchell-lab/rodeo2#requirements). It looks like the current version of RREFinder doesn't allow it to be called from other tools, so I've created a fork [here](https://github.com/the-mitchell-lab/RREFinder) that you can install.

Like other tools, once you've downloaded the RREFinder directory and set it up, you will need to add the root to your path, i.e.

```
export PATH=$PATH:/path/to/RREFinder
```

**Comment by fallinwind** [comment]
https://github.com/the-mitchell-lab/RREFinder this fork is "404 not found"

**Comment by fallinwind** [comment]
problem solved, install precision mode of RREFinder.

https://github.com/Alexamk/RREFinder
Clone the repository.
Install the included conda environment with `conda env create -f RREfinder.yml`
At this point you can already run RREFinder in precision mode. Use python RRE.py with -m precision or --mode precision to do so.
