### ISSUE TITLE
Rodeo2 freezes and is unable to initiate multiprocessing

### ISSUE THREAD

**Issue by somakchowdhury** [the-mitchell-lab/rodeo2#3]
Hi @bkille ,

I have a conda environment under which I have installed Rodeo2. 
base environment : `python = 2.7.0`

other dependencies in the dependency stack were installed using 
`conda install hmmer==3.1b2 biopython==1.69 meme==4.12 scikit-learn==0.19`

Pfam databases were then downloaded and pressed in the hmm_dir in the rodeo2-master repo pulled to the hard drive. 

# Run details
1. Created a folder inside master folder 
`mkdir input`

2. Pasted a .gbk file in this folder

3. Directory adjusted
`cd /Users/somakchowdhury/Desktop/DATA/Rodeo2_install_files/rodeo2-master`

4. Running Rodeo2
`python rodeo_main.py -j 12 input/isolate_67a_contigs.gbk`

5. Error msg

> Process Process-14:
Traceback (most recent call last):
  File "/Users/somakchowdhury/miniconda3/envs/Rodeo_v2_env/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/Users/somakchowdhury/miniconda3/envs/Rodeo_v2_env/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/somakchowdhury/Desktop/DATA/Rodeo2_install_files/rodeo2-master/record_processing.py", line 138, in fill_request_queue
    gb_handles = [open(query.split('\t')[1])]

6. Terminated the process with `cnrt-C`
>IndexError: list index out of range
^C2020-02-06 10:37:06,356 - rodeo_main - CRITICAL - Keyboard interrupt recieved. Shutting down RODEO.
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing
2020-02-06 10:37:06,356 - record_processing - CRITICAL - KeyboardInterrupt recieved during record processing

Note: Rodeo produces the output files but are blank thus concluding it freezes due to the error. 

# OS information : 
`sw_vers`
>ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132

Would much appreciate any insights on how to correct the issue. 

Best,
Somak

**Comment by somakchowdhury** [comment]
# Follow up

Ran rodeo on a gbk from entrez and it is able to provide an output. I am guessing local .gbk generated via Prokka v3.14 or v3.13 are not compatible?

**Comment by bkille** [comment]
Hi @somakchowdhury, to use .gbk files, you must provide an input .txt file where each line has the query accession followed by the `.gbk` record (separated by a tab).

**Comment by somakchowdhury** [comment]
Thank you @bkille for solution. 

Will try to implement this. It would be nice if this prominently stated somewhere in the documentation (Maybe I missed it?). 

Closing for now, will reopen if I run into trouble implementing your solution. Thanks again!
